//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENCUESTA_MOVIL
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int negro = 2131034112;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int azteca = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barraGrisBotonera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int barraGrisObscuro = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Barraprincipal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_radio_off = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_radio_on = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btnAceptar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btnAceptar1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btnAceptar2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btnAceptar3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btnAceptarEncuesta = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btnAceptarsalir = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int buttonAceptar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int buttonAceptar1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int buttonAceptar2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int buttonAceptar3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int buttonAnterior = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int buttonHome = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int buttonSiguiente = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int encabezadoandroid = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int EncabezadoConTitulo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int EncabezadoSinTitulo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Encuesta = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int encuestaAndroidFUENTE = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int FondoEncuestas = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int FondoLoginAndroid = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int headerandroid = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int HeaderEncuestas = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int lineaH = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int radio = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int radioButtonOFF = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int radioButtonON = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int rdb = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int segmentoResultados = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int splash = 2130837539;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int CountPregunta = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int Linea = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int List = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int btnAceptaAccion = 2131230740;
			
			// aapt resource value: 0x7f080011
			public const int btnAceptar = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int btnAceptarFin = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int btnAceptarInicio = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int btnAtras = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int btnInicio = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int layoutDialog = 2131230739;
			
			// aapt resource value: 0x7f080002
			public const int layoutFin = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int layoutInicio = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int lblMensajeBienvenida = 2131230725;
			
			// aapt resource value: 0x7f080012
			public const int lblMensajeDialog = 2131230738;
			
			// aapt resource value: 0x7f080001
			public const int lblMensajeFin = 2131230721;
			
			// aapt resource value: 0x7f08000d
			public const int lblPregunta = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int lblTituloBienvenida = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int lblTituloFin = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout1 = 2131230736;
			
			// aapt resource value: 0x7f080008
			public const int text1 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int textView1 = 2131230729;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FinEncuesta = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Inicial = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_personalizado = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MensajeSINO = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int destroy = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int local_service_label = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int local_service_started = 2131099650;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int BulletPoint = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int CustomTheme = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int RadioButton = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int Text = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int Text_Definition = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int Text_Loading = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Text_WordTitle = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Text_WordType = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int Theme_Shelves = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int Theme_Splash = 2131165192;
			
			private Style()
			{
			}
		}
	}
}
