//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace ENCUESTA_MOVIL.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSEncuestaMovilSoap", Namespace="http://tempuri.org/")]
    public partial class WSEncuestaMovil : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ObtenerDispositivoNumeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneEncuestaPorDispositivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaCoordenadasDispositivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificacionEncuestapendienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaEncuestaContestadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSEncuestaMovil() {
            this.Url = "http://localhost:56522/WSEncuestaMovil.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerDispositivoNumeroCompletedEventHandler ObtenerDispositivoNumeroCompleted;
        
        /// <remarks/>
        public event ObtieneEncuestaPorDispositivoCompletedEventHandler ObtieneEncuestaPorDispositivoCompleted;
        
        /// <remarks/>
        public event GuardaCoordenadasDispositivoCompletedEventHandler GuardaCoordenadasDispositivoCompleted;
        
        /// <remarks/>
        public event NotificacionEncuestapendienteCompletedEventHandler NotificacionEncuestapendienteCompleted;
        
        /// <remarks/>
        public event GuardaEncuestaContestadaCompletedEventHandler GuardaEncuestaContestadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDispositivoNumero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public THE_Dispositivo[] ObtenerDispositivoNumero(double NumeroTelefono) {
            object[] results = this.Invoke("ObtenerDispositivoNumero", new object[] {
                        NumeroTelefono});
            return ((THE_Dispositivo[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDispositivoNumeroAsync(double NumeroTelefono) {
            this.ObtenerDispositivoNumeroAsync(NumeroTelefono, null);
        }
        
        /// <remarks/>
        public void ObtenerDispositivoNumeroAsync(double NumeroTelefono, object userState) {
            if ((this.ObtenerDispositivoNumeroOperationCompleted == null)) {
                this.ObtenerDispositivoNumeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDispositivoNumeroOperationCompleted);
            }
            this.InvokeAsync("ObtenerDispositivoNumero", new object[] {
                        NumeroTelefono}, this.ObtenerDispositivoNumeroOperationCompleted, userState);
        }
        
        private void OnObtenerDispositivoNumeroOperationCompleted(object arg) {
            if ((this.ObtenerDispositivoNumeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDispositivoNumeroCompleted(this, new ObtenerDispositivoNumeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneEncuestaPorDispositivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TDI_EncuestaDispositivo[] ObtieneEncuestaPorDispositivo(int IdDispositivo, double NumeroTel) {
            object[] results = this.Invoke("ObtieneEncuestaPorDispositivo", new object[] {
                        IdDispositivo,
                        NumeroTel});
            return ((TDI_EncuestaDispositivo[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneEncuestaPorDispositivoAsync(int IdDispositivo, double NumeroTel) {
            this.ObtieneEncuestaPorDispositivoAsync(IdDispositivo, NumeroTel, null);
        }
        
        /// <remarks/>
        public void ObtieneEncuestaPorDispositivoAsync(int IdDispositivo, double NumeroTel, object userState) {
            if ((this.ObtieneEncuestaPorDispositivoOperationCompleted == null)) {
                this.ObtieneEncuestaPorDispositivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneEncuestaPorDispositivoOperationCompleted);
            }
            this.InvokeAsync("ObtieneEncuestaPorDispositivo", new object[] {
                        IdDispositivo,
                        NumeroTel}, this.ObtieneEncuestaPorDispositivoOperationCompleted, userState);
        }
        
        private void OnObtieneEncuestaPorDispositivoOperationCompleted(object arg) {
            if ((this.ObtieneEncuestaPorDispositivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneEncuestaPorDispositivoCompleted(this, new ObtieneEncuestaPorDispositivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardaCoordenadasDispositivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardaCoordenadasDispositivo(double numeroTelDispositivo, string latitud, string longitud, string CercaDe) {
            object[] results = this.Invoke("GuardaCoordenadasDispositivo", new object[] {
                        numeroTelDispositivo,
                        latitud,
                        longitud,
                        CercaDe});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardaCoordenadasDispositivoAsync(double numeroTelDispositivo, string latitud, string longitud, string CercaDe) {
            this.GuardaCoordenadasDispositivoAsync(numeroTelDispositivo, latitud, longitud, CercaDe, null);
        }
        
        /// <remarks/>
        public void GuardaCoordenadasDispositivoAsync(double numeroTelDispositivo, string latitud, string longitud, string CercaDe, object userState) {
            if ((this.GuardaCoordenadasDispositivoOperationCompleted == null)) {
                this.GuardaCoordenadasDispositivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaCoordenadasDispositivoOperationCompleted);
            }
            this.InvokeAsync("GuardaCoordenadasDispositivo", new object[] {
                        numeroTelDispositivo,
                        latitud,
                        longitud,
                        CercaDe}, this.GuardaCoordenadasDispositivoOperationCompleted, userState);
        }
        
        private void OnGuardaCoordenadasDispositivoOperationCompleted(object arg) {
            if ((this.GuardaCoordenadasDispositivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaCoordenadasDispositivoCompleted(this, new GuardaCoordenadasDispositivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificacionEncuestapendiente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NotificacionEncuestapendiente(int IdDispositivo, double NumeroTel) {
            object[] results = this.Invoke("NotificacionEncuestapendiente", new object[] {
                        IdDispositivo,
                        NumeroTel});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void NotificacionEncuestapendienteAsync(int IdDispositivo, double NumeroTel) {
            this.NotificacionEncuestapendienteAsync(IdDispositivo, NumeroTel, null);
        }
        
        /// <remarks/>
        public void NotificacionEncuestapendienteAsync(int IdDispositivo, double NumeroTel, object userState) {
            if ((this.NotificacionEncuestapendienteOperationCompleted == null)) {
                this.NotificacionEncuestapendienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificacionEncuestapendienteOperationCompleted);
            }
            this.InvokeAsync("NotificacionEncuestapendiente", new object[] {
                        IdDispositivo,
                        NumeroTel}, this.NotificacionEncuestapendienteOperationCompleted, userState);
        }
        
        private void OnNotificacionEncuestapendienteOperationCompleted(object arg) {
            if ((this.NotificacionEncuestapendienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificacionEncuestapendienteCompleted(this, new NotificacionEncuestapendienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardaEncuestaContestada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardaEncuestaContestada(int IdDispositivo, int IdEncuesta, string[] PreguntaRespuesta, double NumeroTel) {
            object[] results = this.Invoke("GuardaEncuestaContestada", new object[] {
                        IdDispositivo,
                        IdEncuesta,
                        PreguntaRespuesta,
                        NumeroTel});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardaEncuestaContestadaAsync(int IdDispositivo, int IdEncuesta, string[] PreguntaRespuesta, double NumeroTel) {
            this.GuardaEncuestaContestadaAsync(IdDispositivo, IdEncuesta, PreguntaRespuesta, NumeroTel, null);
        }
        
        /// <remarks/>
        public void GuardaEncuestaContestadaAsync(int IdDispositivo, int IdEncuesta, string[] PreguntaRespuesta, double NumeroTel, object userState) {
            if ((this.GuardaEncuestaContestadaOperationCompleted == null)) {
                this.GuardaEncuestaContestadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaEncuestaContestadaOperationCompleted);
            }
            this.InvokeAsync("GuardaEncuestaContestada", new object[] {
                        IdDispositivo,
                        IdEncuesta,
                        PreguntaRespuesta,
                        NumeroTel}, this.GuardaEncuestaContestadaOperationCompleted, userState);
        }
        
        private void OnGuardaEncuestaContestadaOperationCompleted(object arg) {
            if ((this.GuardaEncuestaContestadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaEncuestaContestadaCompleted(this, new GuardaEncuestaContestadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class THE_Respuestas {
        
        private int idRespuestaField;
        
        private THE_Preguntas idPreguntaField;
        
        private string respuestaDescripcionField;
        
        private int idSiguientePreguntaField;
        
        private char respuestaEstatusField;
        
        private string descSigPregField;
        
        /// <remarks/>
        public int IdRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public THE_Preguntas IdPregunta {
            get {
                return this.idPreguntaField;
            }
            set {
                this.idPreguntaField = value;
            }
        }
        
        /// <remarks/>
        public string RespuestaDescripcion {
            get {
                return this.respuestaDescripcionField;
            }
            set {
                this.respuestaDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public int IdSiguientePregunta {
            get {
                return this.idSiguientePreguntaField;
            }
            set {
                this.idSiguientePreguntaField = value;
            }
        }
        
        /// <remarks/>
        public char RespuestaEstatus {
            get {
                return this.respuestaEstatusField;
            }
            set {
                this.respuestaEstatusField = value;
            }
        }
        
        /// <remarks/>
        public string DescSigPreg {
            get {
                return this.descSigPregField;
            }
            set {
                this.descSigPregField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class THE_Preguntas {
        
        private int idPreguntaField;
        
        private string preguntaDescField;
        
        private THE_Encuesta idEncuestaField;
        
        private THE_Preguntas[] listaPreguntasField;
        
        private THE_Respuestas[] listaRespuestasField;
        
        private System.DateTime fechaCreaField;
        
        private char estatusField;
        
        /// <remarks/>
        public int IdPregunta {
            get {
                return this.idPreguntaField;
            }
            set {
                this.idPreguntaField = value;
            }
        }
        
        /// <remarks/>
        public string PreguntaDesc {
            get {
                return this.preguntaDescField;
            }
            set {
                this.preguntaDescField = value;
            }
        }
        
        /// <remarks/>
        public THE_Encuesta IdEncuesta {
            get {
                return this.idEncuestaField;
            }
            set {
                this.idEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public THE_Preguntas[] ListaPreguntas {
            get {
                return this.listaPreguntasField;
            }
            set {
                this.listaPreguntasField = value;
            }
        }
        
        /// <remarks/>
        public THE_Respuestas[] ListaRespuestas {
            get {
                return this.listaRespuestasField;
            }
            set {
                this.listaRespuestasField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCrea {
            get {
                return this.fechaCreaField;
            }
            set {
                this.fechaCreaField = value;
            }
        }
        
        /// <remarks/>
        public char Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class THE_Encuesta {
        
        private int idEncuestaField;
        
        private string nombreEncuestaField;
        
        private System.DateTime fechaCreaEncuestaField;
        
        private string fechaLimiteEncuestaField;
        
        private THE_Empleado empleadoLlavePrimariaField;
        
        private TDI_Estatus idEstatusField;
        
        private THE_Preguntas[] lstPregField;
        
        private char encuestaStatField;
        
        private string nombreEstatusField;
        
        /// <remarks/>
        public int IdEncuesta {
            get {
                return this.idEncuestaField;
            }
            set {
                this.idEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public string NombreEncuesta {
            get {
                return this.nombreEncuestaField;
            }
            set {
                this.nombreEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreaEncuesta {
            get {
                return this.fechaCreaEncuestaField;
            }
            set {
                this.fechaCreaEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public string FechaLimiteEncuesta {
            get {
                return this.fechaLimiteEncuestaField;
            }
            set {
                this.fechaLimiteEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public THE_Empleado EmpleadoLlavePrimaria {
            get {
                return this.empleadoLlavePrimariaField;
            }
            set {
                this.empleadoLlavePrimariaField = value;
            }
        }
        
        /// <remarks/>
        public TDI_Estatus IdEstatus {
            get {
                return this.idEstatusField;
            }
            set {
                this.idEstatusField = value;
            }
        }
        
        /// <remarks/>
        public THE_Preguntas[] LstPreg {
            get {
                return this.lstPregField;
            }
            set {
                this.lstPregField = value;
            }
        }
        
        /// <remarks/>
        public char EncuestaStat {
            get {
                return this.encuestaStatField;
            }
            set {
                this.encuestaStatField = value;
            }
        }
        
        /// <remarks/>
        public string NombreEstatus {
            get {
                return this.nombreEstatusField;
            }
            set {
                this.nombreEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class THE_Empleado {
        
        private int empleadoLlavePrimariaField;
        
        private string empleadoNombreField;
        
        private string empleadoApellPaternoField;
        
        private string empleadoApellMaternoField;
        
        private string empleadoUsuaField;
        
        private char empleadoEstatusField;
        
        /// <remarks/>
        public int EmpleadoLlavePrimaria {
            get {
                return this.empleadoLlavePrimariaField;
            }
            set {
                this.empleadoLlavePrimariaField = value;
            }
        }
        
        /// <remarks/>
        public string EmpleadoNombre {
            get {
                return this.empleadoNombreField;
            }
            set {
                this.empleadoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EmpleadoApellPaterno {
            get {
                return this.empleadoApellPaternoField;
            }
            set {
                this.empleadoApellPaternoField = value;
            }
        }
        
        /// <remarks/>
        public string EmpleadoApellMaterno {
            get {
                return this.empleadoApellMaternoField;
            }
            set {
                this.empleadoApellMaternoField = value;
            }
        }
        
        /// <remarks/>
        public string EmpleadoUsua {
            get {
                return this.empleadoUsuaField;
            }
            set {
                this.empleadoUsuaField = value;
            }
        }
        
        /// <remarks/>
        public char EmpleadoEstatus {
            get {
                return this.empleadoEstatusField;
            }
            set {
                this.empleadoEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TDI_Estatus {
        
        private int idEstatusField;
        
        private string estatusDescripcionField;
        
        private char estatusDispositivoField;
        
        /// <remarks/>
        public int IdEstatus {
            get {
                return this.idEstatusField;
            }
            set {
                this.idEstatusField = value;
            }
        }
        
        /// <remarks/>
        public string EstatusDescripcion {
            get {
                return this.estatusDescripcionField;
            }
            set {
                this.estatusDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public char EstatusDispositivo {
            get {
                return this.estatusDispositivoField;
            }
            set {
                this.estatusDispositivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TDI_EncuestaDispositivo {
        
        private THE_Dispositivo idDispositivoField;
        
        private THE_Encuesta idEncuestaField;
        
        private THE_Encuesta[] listaEncuestaField;
        
        private TDI_Estatus idEstatusField;
        
        private THE_Preguntas[] listPregField;
        
        /// <remarks/>
        public THE_Dispositivo IdDispositivo {
            get {
                return this.idDispositivoField;
            }
            set {
                this.idDispositivoField = value;
            }
        }
        
        /// <remarks/>
        public THE_Encuesta IdEncuesta {
            get {
                return this.idEncuestaField;
            }
            set {
                this.idEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public THE_Encuesta[] ListaEncuesta {
            get {
                return this.listaEncuestaField;
            }
            set {
                this.listaEncuestaField = value;
            }
        }
        
        /// <remarks/>
        public TDI_Estatus IdEstatus {
            get {
                return this.idEstatusField;
            }
            set {
                this.idEstatusField = value;
            }
        }
        
        /// <remarks/>
        public THE_Preguntas[] ListPreg {
            get {
                return this.listPregField;
            }
            set {
                this.listPregField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class THE_Dispositivo {
        
        private int idDispositivoField;
        
        private string numerodelTelefonoField;
        
        private string modeloField;
        
        private string marcaField;
        
        private string imagenTelefonoField;
        
        private string dispositivoDescField;
        
        private string dispositivoMeidField;
        
        private string dispositivoMdnField;
        
        private char dispositivoEstatusField;
        
        private string colorEstatusField;
        
        private string estatusCheckField;
        
        private string chkEnabledField;
        
        private string strColorField;
        
        /// <remarks/>
        public int IdDispositivo {
            get {
                return this.idDispositivoField;
            }
            set {
                this.idDispositivoField = value;
            }
        }
        
        /// <remarks/>
        public string NumerodelTelefono {
            get {
                return this.numerodelTelefonoField;
            }
            set {
                this.numerodelTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public string ImagenTelefono {
            get {
                return this.imagenTelefonoField;
            }
            set {
                this.imagenTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string DispositivoDesc {
            get {
                return this.dispositivoDescField;
            }
            set {
                this.dispositivoDescField = value;
            }
        }
        
        /// <remarks/>
        public string DispositivoMeid {
            get {
                return this.dispositivoMeidField;
            }
            set {
                this.dispositivoMeidField = value;
            }
        }
        
        /// <remarks/>
        public string DispositivoMdn {
            get {
                return this.dispositivoMdnField;
            }
            set {
                this.dispositivoMdnField = value;
            }
        }
        
        /// <remarks/>
        public char DispositivoEstatus {
            get {
                return this.dispositivoEstatusField;
            }
            set {
                this.dispositivoEstatusField = value;
            }
        }
        
        /// <remarks/>
        public string ColorEstatus {
            get {
                return this.colorEstatusField;
            }
            set {
                this.colorEstatusField = value;
            }
        }
        
        /// <remarks/>
        public string EstatusCheck {
            get {
                return this.estatusCheckField;
            }
            set {
                this.estatusCheckField = value;
            }
        }
        
        /// <remarks/>
        public string ChkEnabled {
            get {
                return this.chkEnabledField;
            }
            set {
                this.chkEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string StrColor {
            get {
                return this.strColorField;
            }
            set {
                this.strColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerDispositivoNumeroCompletedEventHandler(object sender, ObtenerDispositivoNumeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDispositivoNumeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDispositivoNumeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public THE_Dispositivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((THE_Dispositivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtieneEncuestaPorDispositivoCompletedEventHandler(object sender, ObtieneEncuestaPorDispositivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneEncuestaPorDispositivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneEncuestaPorDispositivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TDI_EncuestaDispositivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TDI_EncuestaDispositivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardaCoordenadasDispositivoCompletedEventHandler(object sender, GuardaCoordenadasDispositivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaCoordenadasDispositivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaCoordenadasDispositivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void NotificacionEncuestapendienteCompletedEventHandler(object sender, NotificacionEncuestapendienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotificacionEncuestapendienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotificacionEncuestapendienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardaEncuestaContestadaCompletedEventHandler(object sender, GuardaEncuestaContestadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaEncuestaContestadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaEncuestaContestadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591